package com.sihabudin.learngooglemaps2022

const val MAP_STYLE ="Map Style"
const val MAP_TYPE ="Map Type"
const val MAP_BUILDING3D ="Building 3D"
const val MAP_MAXMINZOOM ="Max-Min Zoom"
const val MAP_UPDATE_CAMERA_POSITION ="Update Camera Position"
const val MAP_BOUNDARIES = "Setting boundaries on the map"
const val MAP_RESTRICT_SCROLL = "Restrict user from scrolling"
const val MAP_ANIMATE_CAMERA = "Animate Camera Movement"
const val MAP_SINGLE_LONG_CLICK = "Single / Long Click Event"
const val MAP_OBJECT_MARKER = "Store data object in a Marker"
const val MAP_MARKER_DRAGGING ="Enable Marker Dragging"
const val MAP_MARKER_CUSTOM = "Marker Customization"
const val MAP_INFO_WINDOW ="Info Window"
const val MAP_INFO_WINDOW_CUSTOM ="Info Window Custom"
const val MAP_POLYLINES = "Introduction Polyline"
const val MAP_POLYGONS = "Introduction Polygon"
const val MAP_CIRCLE = "Introduction Circle"
const val MAP_CUSTOM_POLYLINES = "Custom Polyline"
const val MAP_GROUND_OVERLAY ="Ground Overlay"